### ISSUE TITLE
Using example

### ISSUE THREAD

**Issue by ProgrammerFB** [DMXControl/ArtNetSharp#3]
Hi,

I want to use this package in a project, but i don't see any documentation and i don't know how to exactly use it.

I tried run examples, but i don't see any effects of the program. When I transmit data by QLC+ read it on The ArtNetominator it's working, but when I'm trying to transmit or recive DMX data by program using ArtNetSharp I don't see any effecst.

I would appreciate if you could show me a working example of using this package. What I need most is ArtNet receiver.

Thank you in advance

**Comment by patrick-dmxc** [comment]
Send me a Whireshark dump while u do what you have done.

**Comment by patrick-dmxc** [comment]
So, i Downloaded QLC+ 5 and tested it my self,
Use Node Output Example i updated now, it should work out of the box.
What you properbly not have done Commented out these lines:
`var broadcastIp = new IPAddress(new byte[] { 2, 255, 255, 255 });`
`ArtNet.Instance.NetworkClients.ToList().ForEach(ncb => ncb.Enabled = IPAddress.Equals(broadcastIp, ncb.BroadcastIpAddress));`
Which limited the Example to only work on a 2.0.0.0/8 Network.
Additionaly QLC+ is sending per default on Universe 0 The Example was listenening on 1-32, i changed this to 0-31
But what i discoverd is QLC+ is not using ArtNet as Specified, because it sends DMX as Broadcast, this is prohibited since ArtNet 4 
Question, whi you use QLC+ and not [DMXControl 3](https://www.dmxcontrol.de/en/dmxcontrol-3/features.html)
